name: Simply pull to get the latest changes

on:
  issue_comment:
    types: [created] # 댓글이 생성되었을 때 트리거

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. 조건: 'refresh'라는 댓글일 때만 실행
      - name: SSH to server
        if: ${{ github.event.comment.body == 'refresh' }} # 여기에서 조건 사용
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            git pull
